### PR TITLE
Fix/pom corrected

### PR DESCRIPTION
**Pull request by asturio**
Hi there,

here is a small pom cleanup, where the used dependencies are really declared in the user-module, and not used dependencies are removed.

I also added a Xlint compiler flag, so we can cleanup the code to be more Java 6+ like (generics and the like)

Compiles and the Tests run.

### CODE REVIEW

**Comment by andreasrosdal** [comment]
Thanks for this contribution to OpenPDF. 

I have retired from maintaining this library. Can you please contact @bengolder to get this pull-request reviewed? Perhaps he could also give you commit access to this repository if you are interested.

**Comment by asturio** [comment]
Is @bengolder the only reviewer for this project? I just created the pull request. There was no way to assign this to an specific developer/user.

**Comment by andreasrosdal** [comment]
Try @bengolder or @daviddurand 

https://github.com/daviddurand
or benjamin.j.golder at gmail.com

**Comment by andreasrosdal** [comment]
Perhaps @nwinkler can help?

**Comment by andreasrosdal** [comment]
@asturio  Perhaps you can ask @tlxtellef for commit access?

**Comment by tlxtellef** [comment]
These changes looks good to me. @asturio I can give you write access if you plan on doing more work on this project. I will be looking at the other pull request.

**Comment by asturio** [comment]
Hi @tlxtellef , write access could be nice. Yeah, I'm planing be active here. I'll promise to be careful.

**Pull request merged**
