### PR TITLE
Improve if statement readability and fix documentation typo

### PR DESCRIPTION
**Pull request by dukbong**
## Description of the new Feature/Bugfix

The pull request involves code modifications aimed at maintenance and readability improvements rather than introducing new features or fixing bugs. Specifically, I refactored the if statements to enhance code readability. Additionally, I corrected a typo in the documentation.

Related Issue: #

## Unit-Tests for the new Feature/Bugfix

- [ ] Unit-Tests added to reproduce the bug
- [ ] Unit-Tests added to the added feature

## Compatibilities Issues

The changes made for code maintenance do not introduce any compatibility issues. Method signatures remain unchanged, and existing functionalities are not affected.

## Testing details

To verify the code maintenance improvements, review the modified code and ensure that the if statements are now easier to understand and maintain. Confirm that the documentation typo has been corrected. Although no new functionality is introduced, it's advisable to run existing unit tests to ensure that the changes have not inadvertently caused any regressions. Additionally, consider performing manual testing to validate the modifications thoroughly.

#### Comment

This is my first attempt at contributing to an open-source project. It's also a project I've been using lately, and as I'm currently studying code that's easier to maintain, I've tried applying some of those principles to the codebase. I understand you must be busy, but I would greatly appreciate it if you could provide any feedback or suggestions on the changes I've made. Thank you.

### CODE REVIEW

**Comment by dukbong** [comment]
> ## Description of the new Feature/Bugfix
> The pull request involves code modifications aimed at maintenance and readability improvements rather than introducing new features or fixing bugs. Specifically, I refactored the if statements to enhance code readability. Additionally, I corrected a typo in the documentation.
> 
> Related Issue: #
> 
> ## Unit-Tests for the new Feature/Bugfix
> * [ ]  Unit-Tests added to reproduce the bug
> * [ ]  Unit-Tests added to the added feature
> 
> ## Compatibilities Issues
> The changes made for code maintenance do not introduce any compatibility issues. Method signatures remain unchanged, and existing functionalities are not affected.
> 
> ## Testing details
> To verify the code maintenance improvements, review the modified code and ensure that the if statements are now easier to understand and maintain. Confirm that the documentation typo has been corrected. Although no new functionality is introduced, it's advisable to run existing unit tests to ensure that the changes have not inadvertently caused any regressions. Additionally, consider performing manual testing to validate the modifications thoroughly.
> 
> #### Comment
> This is my first attempt at contributing to an open-source project. It's also a project I've been using lately, and as I'm currently studying code that's easier to maintain, I've tried applying some of those principles to the codebase. I understand you must be busy, but I would greatly appreciate it if you could provide any feedback or suggestions on the changes I've made. Thank you.

**Comment by asturio** [comment]
Readability is very important. Thank you for your contribution.

**Comment by asturio** [comment]
It's merged, but I corrected the formatting of the if's back, as the indentation was a little bit strange.
You wrote:
```java
           if (b2 >= a1 && !(-3 <= d && d <= 3)) { 
                a2 = finddiff2(dataBp, offsetData, a1, rowpixels, pixel(dataBp, offsetData, a1));
                handleHorizontalMode(a0, a1, a2);
                a0 = a2;
                } else if (b2 >= a1) { 
                    putcode(vcodes[d + 3]);
                    a0 = a1;
                    } else { 
                        putcode(passcode);
                        a0 = b2;
                        }
```
but the formatting should be:
```java
            if (b2 >= a1 && !(-3 <= d && d <= 3)) {
                a2 = finddiff2(dataBp, offsetData, a1, rowpixels, pixel(dataBp, offsetData, a1));
                handleHorizontalMode(a0, a1, a2);
                a0 = a2;
            } else if (b2 >= a1) {
                putcode(vcodes[d + 3]);
                a0 = a1;
            } else {
                putcode(passcode);
                a0 = b2;
            }
```

**Comment by dukbong** [comment]
Thank you!
I didn't realize there was an indentation issue 😿 
I'm really glad that the changes I made were incorporated into the code!!

**Pull request merged**
