### PR TITLE
#837 Modified PdfPTable add cell method to return cell (*Breaking Changes*)

### PR DESCRIPTION
**Pull request by jaybob007**
Updated PdfPTable addCell methods to return the cell that was added.

Related Issue: #837

### CODE REVIEW

**Comment by jaybob007** [comment]
Can the hacktoberfest-accepted label be added to this PR?

**Comment by lmove** [comment]
Hi! Our tool [BreakBot](https://github.com/alien-tools/breakbot) found that this pull request introduces **5 breaking changes** and they appear to impact **1 of your clients**. You can find the full BreakBot report in our fork repository: [report for PR#844](https://github.com/breakbot-playground/OpenPDF/pull/1/checks).

We hope this information is valuable to you, and apologize otherwise. If you're willing to help, we would kindly ask for your help to fill in a [5-minutes survey](https://survey.breakbot.net/index.php/418865/newtest/Y?ID=LibrePDF-OpenPDF-844) about the report. Your feedback will help us improve the tool and provide a better experience for users in the future!

**Comment by asturio** [comment]
Will add this to 1.4.0 because of breaking changes.

**Comment by andreasrosdal** [comment]
Could this be implemented in a non-breaking way? is it really a breaking change when changing a method from void to returning an object?

**Comment by laeubi** [comment]
Thank you :+1:

**Pull request merged**
