### PR TITLE
Remove warnings 5

### PR DESCRIPTION
**Pull request by sixdouglas**
Adding some suppressWarning on deprecated methods.
Moving raw types to Generic corresponding ones.
In FdfWriter#removeField(String) I've changed a little the internal method code to avoid having the `hist` List (line 133) containing either some Map or some String> I've separated the content on two different variables, one is a List<Map>, and the other one is a List<String>.

### CODE REVIEW

**Comment by sixdouglas** [comment]
I was wondering about using ArrayList<> instead of List<> as return values for functions. And I've just seen your previous PR in this way. So I'm going to rework this PR and the remaining files I have left, in this way.

**Comment by andreasrosdal** [comment]
@albfernandez  @asturio  Can you please help review this.

**Comment by sixdouglas** [comment]
Rework done. Ready for Review

**Comment by sixdouglas** [comment]
Build failed for JDK 12 but works in local for this version. Do you have any hint on how to solve this problem?

**Comment by andreasrosdal** [comment]
Thanks for the update! I restarted the Travis-CI build and now it works.

**Comment by andreasrosdal** [comment]
@sixdouglas Does this change break API compatibility?

**Comment by sixdouglas** [comment]
@andreasrosdal I tried to minimized as much as could the breaking changes. Normally there are none.

**Pull request merged**
