### PR TITLE
Glyph layout - See Issue #442

### PR DESCRIPTION
**Pull request by vk-github18**
Pull request for issue #442 Accented Letters composed of Unicode base letter and combining accent are rendered incorrectly. 

The position of glyphs is computed with statndard Java AWT methods.
The output should be correct for all characters and sequences of DIN SPEC 91379.
Eventually other scripts are also rendered correctly especially with Java versions >= 1.9 using HarfBuzz for rendering - this is not in the scope of this change.

See the example GlyphLayoutDinSpec91379.java

### CODE REVIEW

**Comment by codecracker2014** [comment]
@vk-github18 can you check [this wiki ](https://github.com/LibrePDF/OpenPDF/wiki/Multi-byte-character-language-support-with-TTF-fonts) and see if this can solve #442

**Comment by vk-github18** [comment]
@codecracker2014 FopGlyphProcessor does glyph substitution, not glyph positioning, so it can not solve #442

**Comment by codecracker2014** [comment]
@vk-github18 can you share output with FopGlyphProcessor enabled.

**Comment by vk-github18** [comment]
@codecracker2014 The output would not change with FopGlyphProcessor enabled, because it will not be called. The LayoutProcessor always calls showText(glyphVector),

**Comment by vk-github18** [comment]
Output of example programs:
[GlyphLayoutDocumentDinSpec91379.pdf](https://github.com/LibrePDF/OpenPDF/files/5555367/GlyphLayoutDocumentDinSpec91379.pdf)
[GlyphLayoutFormDinSpec91379.pdf](https://github.com/LibrePDF/OpenPDF/files/5555369/GlyphLayoutFormDinSpec91379.pdf)

**Comment by asturio** [comment]
@codecracker2014 , @vk-github18 
Any objections in this PR? It looks OK for me. (will merge in 3 days, if no one is against it :-) )

**Review by asturio — APPROVED** [review]
The results look good. Code is clean!

**Comment by vk-github18** [comment]
I need to provide another correction before merging.

**Comment by vk-github18** [comment]
Code should be ok now, the result of the examples is: 

[GlyphLayoutDocumentDinSpec91379.pdf](https://github.com/LibrePDF/OpenPDF/files/5591805/GlyphLayoutDocumentDinSpec91379.pdf)
[GlyphLayoutFormDinSpec91379.pdf](https://github.com/LibrePDF/OpenPDF/files/5591806/GlyphLayoutFormDinSpec91379.pdf)

**Comment by asturio** [comment]
It's a nice improvement. I think there still some issues with "apostrophes" like in c', or t'. But other glyphs are looking great.

**Comment by vk-github18** [comment]
Thanks for merging the request.
I am not sure, which combinations you refer to. Some problems are addressed in https://github.com/googlefonts/noto-fonts/issues/1882

**Comment by vk-github18** [comment]
For reference I am adding a list of the sequences with codepoint and name.
[GlyphLayoutDinSpec91379Sequences.pdf](https://github.com/LibrePDF/OpenPDF/files/5612518/GlyphLayoutDinSpec91379Sequences.pdf)

**Comment by asturio** [comment]
> For reference I am adding a list of the sequences with codepoint and name.
> [GlyphLayoutDinSpec91379Sequences.pdf](https://github.com/LibrePDF/OpenPDF/files/5612518/GlyphLayoutDinSpec91379Sequences.pdf)

Everything fine. I assumed the display of "LATIN CAPITAL LETTER * WITH COMBINING COMMA ABOVE RIGHT" was wrong. But it is exactly as with the reference.

Thank you again for this very nice PR :+1:

**Comment by vk-github18** [comment]
@asturio You are right, the display of some letters with "COMBINING COMMA ABOVE RIGHT" is wrong, this is caused by a bug of the Noto Sans fonts, see https://github.com/googlefonts/noto-fonts/issues/1882

**Comment by sriharsha9598** [comment]
Hey Guyz,

I am using OpenPDF 1.3.43 in my library and need to accurately measure the width of a phrase. However, in some languages, certain glyphs are processed and merged into proper characters when `LayoutProcessor.enable()` is used.  

Methods such as `ColumnText.getWidth()` and `Chunk.getWidthPoint()` return the width of the unprocessed text, which includes separate glyphs before they are merged. After `LayoutProcessor` processes the text, multiple glyphs are combined, reducing the actual width. However, I have not found a way to retrieve the width of the processed text after these transformations.  

Could you confirm if there is a method to obtain the correct width after `LayoutProcessor` has been applied? Any insights or guidance would be greatly appreciated.  

Thank you!

CC: @vk-github18 @asturio

**Pull request merged**
