### PR TITLE
Bugfixes by drawing text in PdfGraphics2D

### PR DESCRIPTION
**Pull request by V-F**
BUG PdfGraphics2D:
- fixed position of visible parts of text (parts that can be displayed with the given font) and preventing alignment of the text in width if text contains characters, that cannot be displayed;
- fixed displaying text with logical fonts in windows OS (Displaying text with the composite fonts).

Test use case for seeing bug/fix: drawing string "对话 [Dialog]" with the "Dialog" font.

### CODE REVIEW

**Comment by andreasrosdal** [comment]
Thanks! 👍

**Comment by V-F** [comment]
Please fix line 1802 -> it should be &&. Thanks in advance.

**Comment by andreasrosdal** [comment]
@V-F I have fixed this now. Can you please test and verify this change again?

It is absolutely important that you yourself test and check the quality of your contributions before submitting it as a pull request to this project.

**Comment by V-F** [comment]
Thank you. I have checked - everything works as it should. It was my misprint that I didn't immediately notice. It could lead to error theoretically, but in any case, I’ll try to avoid these errors.

**Pull request merged**
