### PR TITLE
Bugfix displaying strings with composite fonts

### PR DESCRIPTION
**Pull request by V-F**
BUG PdfGraphics2D: fixed logic with drawing text with composite fonts - check created base font if contains glyph for the given character (since font mapper can be wrong configured/font cannot be embedded due to licensing restrictions and so on its need to check base font instead of java font). Fixed enabling logic with drawing text with composite fonts also for the nix OS.
P.S. Sorry for wrong branch name - it should be composite font.

### CODE REVIEW

**Comment by sixdouglas** [comment]
Hi @V-F ,

Is this fixing any known issue? 
If so, could you make a reference to it using the # followed by its id?
If not, could you open one explaining the problem and giving the smallest sample code possible to reproduce it?

Can you also add a test (unit or sample) to cover these changes? And maybe squashing your commits would be nice.

Thanks for your help

**Comment by V-F** [comment]
Opened issue #315
Sample of code can be used as test unit if you want.

**Comment by codecracker2014** [comment]
@V-F is this issue related to   #297 ?

**Comment by V-F** [comment]
@codecracker2014 no. This relates only for composite fonts ([logical java fonts](https://docs.oracle.com/javase/7/docs/api/java/awt/Font.html)) .
A logical Font might be a composite font, which means that it is composed of different physical fonts to cover different code ranges.

**Pull request merged**
