### PR TITLE
Handling for multiple Catalog pdfs v2

### PR DESCRIPTION
**Pull request by tekurusu**
Related issue: https://github.com/LibrePDF/OpenPDF/issues/135

### CODE REVIEW

**Comment by asturio** [comment]
Do you have any tests for this change?

**Comment by andreasrosdal** [comment]
Presse add a comment to the code explaining what the code does.

Please share a multi catalog PDF where this change can be verified.

**Comment by andreasrosdal** [comment]
Thanks for the attempt and effort in trying to solve this.
I close this pull-request as incorrect. Please try a better solution.

For science and progress, here is how an AGPL project chose to solve this: https://github.com/itext/itextpdf/blob/develop/itext/src/main/java/com/itextpdf/text/pdf/PdfStamperImp.java#L487

**Comment by tekurusu** [comment]
> Thanks for the attempt and effort in trying to solve this.
> I close this pull-request as incorrect. Please try a better solution.
> 
> For science and progress, here is how an AGPL project chose to solve this:
Hi, thanks for replying!

The implementation of iText there seems similar to the one used here? Or are you referring to the declaration of the `root` object after the `info` object? If so, I can still replicate the bug with this change.

Currently looking for a sample file that I can share with you guys.

Apologies for the newbie questions, am just picking up pdf structures and still a bit confused

**Comment by andreasrosdal** [comment]
Thanks. We need to be sure it works.

**Pull request closed without merging**
