### PR TITLE
fix the .HEIC image bug #130

### PR DESCRIPTION
**Pull request by youyumeimei**
## Description of the new Feature/Bugfix
Describe here how you fixed the bug, or implemented the new feature.

Related Issue: #130 

## Unit-Tests for the new Feature/Bugfix
- [ ] Unit-Tests added to reproduce the bug
- [ ] Unit-Tests added to the added feature

## Compatibilities Issues
Is anything broken because of the new code? Any changes in method signatures?
No.

## Testing details
Any other details about how to test the new feature or bugfix?
According to the issue, we write a test file. It can make pdf files and can see them to test whether it is successed.

### CODE REVIEW

**Comment by mluppi** [comment]
I'm reluctant to add this to OpenPDF. Since *im4java* is just a wrapper which uses the ImageMagick CLI, the user would need to have this tool on their path when they want to add a HEIC image. The additional dependencies are not actually needed if the user would transform their HEIC images to PNG in their own code. This would keep OpenPDF focused on what it does best.

**Comment by asturio** [comment]
Hi @youyumeimei , can you take a look at the build errors of this PR? If this compiles I can merge it.

**Comment by asturio** [comment]
@youyumeimei 
The code is not compiling. Can you take a look at it?

**Comment by asturio** [comment]
Is there any change this can be done without lombok and PDFBox?

**Comment by andreasrosdal** [comment]
Please remove the dependency on Pdfbox.

**Pull request closed without merging**
