### PR TITLE
Fix NullPointerException on null rows in table

### PR DESCRIPTION
**Pull request by fellmann**
## Description of the new Feature/Bugfix
Describe here how you fixed the bug, or implemented the new feature.

Related Issue: #1028 

## Unit-Tests for the new Feature/Bugfix
- [x] Unit-Tests added to reproduce the bug

### CODE REVIEW

**Comment by andreasrosdal** [comment]
Thank you for submitting this. There is a compilation error here.

**Comment by fellmann** [comment]
@andreasrosdal This would be my approach. Note the null pointer check in the first loop instead of second.
The first loop (https://github.com/LibrePDF/OpenPDF/pull/1029/files#diff-f8ff0e0467d7f9125d29b3c1f5f96b40a8bb603ae719effd248bdd3f97753d97L882) lists all rows within the rowspan that should be used to distribute the excess height, which is then done in the second loop. So the null check in the first loop is sufficient.
Yet, there are more places where no null check is done, I tried to fix those too.

**Comment by andreasrosdal** [comment]
There is a Codacy Static Code Analysis failure. Can you please fix this?

**Comment by fellmann** [comment]
Am I correct that the tests are not run in the CI build?

**Comment by andreasrosdal** [comment]
https://app.codacy.com/gh/LibrePDF/OpenPDF/pullRequest?prid=13444748

**Pull request merged**
