### PR TITLE
Fix for loading of TIFF with transparency.

### PR DESCRIPTION
**Pull request by tttellef**

### CODE REVIEW

**Comment by andreasrosdal** [comment]
Hei Tellef! Ta kontakt med https://mobile.twitter.com/bgolder for å få tilgang til dette repositoriet.

**Comment by tttellef** [comment]
Is that really necessary for this? Don't you have write access? Besides, wouldn't it be better to just ask @bengolder directly on GitHub?

**Comment by andreasrosdal** [comment]
There are 3 other people who have access. I don't have access any more. These people are @bengolder , @daviddurand and @nwinkler.

**Comment by andreasrosdal** [comment]
Make sure to test this version of OpenPDF very good before considering running it in any web-based economy systems in production. I have accepted most pull-request in order to try to consoludate development of rtfarte/OpenPDF in a single open source branch. Beware that I haven't tested these changes in any web-based economy systems at all.

Maintaining your own fork of this library on GitHub is also a very valid alternative. Or try to contact @bengolder , @daviddurand or @nwinkler. This will take some effort on your part. I don't have access to this repository any more.

**Comment by asturio** [comment]
I don't know a way to contact another developer on GitHub without being this way, in a "discussion".

@andreasrosdal If you don't have write access, why are you the only one reacting to these pull requests? Or the other way 'round. Why are the users with write access not reacting to the requests? That ain't no good.

**Comment by andreasrosdal** [comment]
@asturio I still hope that you or @tttellef will be able to contact one of the three other developers. You probably have to try harder, using some other communcation channel, such as e-mail or twitter. I used to be one of the developers on this project, but made a decision that I had to prioritize other things about one month ago. For quite some time I have been the one reviewing pull-requests to this project. There are now three other developers, but it seems they are not very active. I think you should be able to contact them. Try harder, and not just in this thread. :)

If you are not able to contact them, then you are free to start a new fork on GitHub. Perhaps cooperate with @tttellef. Development can happen in any fork, not just this one. For example, https://github.com/OpenPDF/OpenPDF/ is still available. It is all up to you. Good luck!

**Comment by nwinkler** [comment]
Sorry, I am no longer working on this project - too many other commitments.

**Comment by andreasrosdal** [comment]
@nwinkler Do you still have admin access? Can you please give admin access to @tttellef ?

**Comment by nwinkler** [comment]
No, sorry, don't have admin access anymore...

**Comment by tttellef** [comment]
@andreasrosdal [https://github.com/OpenPDF/OpenPDF/](https://github.com/OpenPDF/OpenPDF/) doesn't exist, 404

**Comment by daviddurand** [comment]
I made a number of fixes, and some changes/improvements to the text extraction API, as I use this PDF library, and did not want to follow to the new license. I was invited to contribute after my branch was pulled into the the new fork.

I don't have a lot of time to be an organizer, but I am happy to participate as I can. Certainly If I fix any more bugs, I will submit my own pull requests.

I have no administrative privileges, so issues like that must be handled by the owner, @bengolder.

**Comment by andreasrosdal** [comment]
@daviddurand You only clicked approve, you didn't merge this pull-request. Please also merge it.

@tttellef Then you need to contact @bengolder to get admin access to this repository.  http://benjamingolder.com  (There is a lot of contact information there.  A whois query to his domain will also give you contact information.)

https://github.com/OpenPDF/OpenPDF/ doesn't exist, but you could create it. You are free to create a fork of this repository. So it is up to the people who want to use this repository to come together, cooperate and create a new fork.

**Comment by andreasrosdal** [comment]
@tttellef You are now admin on this project!

**Comment by andreasrosdal** [comment]
This is how to make a release:  https://github.com/LibrePDF/OpenPDF/wiki/Release-Process

I still have access to make releases to maven central of OpenPDF, so I can probably help to request permission to make released for you, if you want that.

**Comment by bengolder** [comment]
Apologies to everyone regarding the confusion over access. I haven't had time to act as a maintainer and had assumed that others had admin abilities.

**Comment by tttellef** [comment]
@bengolder @andreasrosdal So, making a release is the next thing.

**Comment by andreasrosdal** [comment]
Please read this:  https://github.com/LibrePDF/OpenPDF/wiki/Release-Process

1. Create a new Sonatype JIRA login.
2. If you need anything from me so that you can create releases of OpenPDF, please ask. I have permission to create releases.

**Comment by tttellef** [comment]
@andreasrosdal Well, I lack permissions for the staging profile.

**Comment by andreasrosdal** [comment]
@tttellef Let me know if you want me to do anything then.

**Comment by tttellef** [comment]
@andreasrosdal Then create a release as it seems I can't.

**Comment by andreasrosdal** [comment]
What is your Sonatype account username?

**Comment by tttellef** [comment]
tlxtellef

**Comment by andreasrosdal** [comment]
Please follow the progress here:  https://issues.sonatype.org/browse/OSSRH-35105

**Comment by andreasrosdal** [comment]
Permissions granted.

**Pull request merged**
