### PR TITLE
Replace getBytes with getISOBytes

### PR DESCRIPTION
**Pull request by tulikavijay**
## Description of the new Feature/Bugfix
Describe here how you fixed the bug, or implemented the new feature.

Related Issue: #581 

## Unit-Tests for the new Feature/Bugfix
- [ ] Unit-Tests added to reproduce the bug
- [ ] Unit-Tests added to the added feature

## Compatibilities Issues
Is anything broken because of the new code? Any changes in method signatures?

## Testing details
Any other details about how to test the new feature or bugfix?

- Removed one statement from the unit test as it was failing because of it : LayoutProcessor.enable(java.awt.Font.LAYOUT_RIGHT_TO_LEFT);
- Locally this test - testAwtImage() is failing because of nullpointerException at this line:  final URL systemResource = ClassLoader.getSystemResource("H.gif");

Let me know how to fix these

### CODE REVIEW

**Comment by asturio** [comment]
> @asturio let me know if changes are required

Hi, I want to check that with the Unit-Test. I think it is a little bit strange, that it failed.

**Comment by vk-github18** [comment]
> ## Testing details
> Any other details about how to test the new feature or bugfix?
> 
> * Removed one statement from the unit test as it was failing because of it : LayoutProcessor.enable(java.awt.Font.LAYOUT_RIGHT_TO_LEFT);

This statement is essential for the test and must not be removed.

**Comment by foto-andreas** [comment]
> > @asturio let me know if changes are required
> 
> Hi, I want to check that with the Unit-Test. I think it is a little bit strange, that it failed.

@asturio I think it fails if the system encoding is not compatible like on z/OS (using EBCDIC). So a unit test is always correct for ascii chars on unix or windows.

Andreas

**Comment by nadir35** [comment]
> > > @asturio let me know if changes are required
> > 
> > 
> > Hi, I want to check that with the Unit-Test. I think it is a little bit strange, that it failed.
> 
> @asturio I think it fails if the system encoding is not compatible like on z/OS (using EBCDIC). So a unit test is always correct for ascii chars on unix or windows.
> 
> Andreas

I can confirm that this is indeed the problem scenario. As I described in https://github.com/LibrePDF/OpenPDF/issues/581

@asturio Will this be merged anytime soon?

**Comment by asturio** [comment]
fixed in #642

**Pull request closed without merging**
