### PR TITLE
fix 500 issues

### PR DESCRIPTION
**Pull request by Wugengxian**
## Description of the new Feature/Bugfix
the issue is caused by that pdfCopyFields.addDocument(reader, "1"); which deletes noused pdfObject, but page 1 has the link to page 2. So the solution is to check if adding the noused pdfObject to readers2intrefs.
Related Issue: #500

## Unit-Tests for the new Feature/Bugfix
- [openpdf/src/test/java/com/lowagie/text/pdf/PdfTestBaseTest/nullpointerExceptionTest ] Unit-Tests added to reproduce the bug

## Compatibilities Issues
No

## Testing details
you can change the page to "1,2", and you can find the link of page 1 is valid, so link only be useful when you add the linked page.

### CODE REVIEW

**Comment by asturio** [comment]
Hi @Wugengxian ,

nice PR. Can you rebase your branch to the last master state? GitHub can't merge it safely.

Thanks

**Comment by Wugengxian** [comment]
@asturio
github show me that GitHub can merge it safely.
image

**Comment by asturio** [comment]
I'll merge it manually.

**Comment by asturio** [comment]
Oh, sorry. Looks good now. Let's merge this.

**Comment by asturio** [comment]
> Hi @Wugengxian ,
> 
> nice PR. Can you rebase your branch to the last master state? GitHub can't merge it safely.
> 
> Thanks

I think something went with the rebase wrong. The actual fix is gone.

**Comment by Wugengxian** [comment]
@asturio I have rebased the master branch. Is it ok to merge?

**Pull request merged**
