### PR TITLE
With glyph substitution question mark is coming in PDF

### PR DESCRIPTION
**Pull request by codecracker2014**
In case of glyph substitution occurs for text, glyph array length may change. So limit should be considered while iterating array else null character will get inserted.

### CODE REVIEW

**Comment by asturio** [comment]
Can you write a test for it?

**Comment by codecracker2014** [comment]
@asturio there is already a test case for FopGlyphProcessor.convertToBytesWithGlyphs method (AdvanceTypographyTest.testTypographySubstitution). Current issue can't be replicated for all fonts, currently it's occurring on calibri font as below.
image

**Comment by asturio** [comment]
> Can we include calibri font for test case?

Can it be replicated with Liberation-Fonts? They are already in the repo.

**Comment by codecracker2014** [comment]
I tried all Liberation-Fonts this issue is not reproducing.
With Liberation-Font:
image
With calibri:
image

**Comment by codecracker2014** [comment]
Reproducing with Viaoda Libre Font added test case. look 'instruction' has 11 characters but after glyph substitution it is represented with 9 glyphs.
image

**Pull request merged**
