### PR TITLE
Enable kerning and ligatures for LayoutProcessor

### PR DESCRIPTION
**Pull request by vk-github18**
## Description of the new Feature/Bugfix
1. Kerning and ligatures can be enabled for LayoutProcessor by calling LayoutProcessor.enableKernLiga();
2. Updates for final standard DIN 91379

### GlyphLayoutDocumentDin91379.java 
Shows all letters and sequences of DIN 91379 in a new
PDF-document.
[GlyphLayoutDocumentDin91379.pdf](https://github.com/LibrePDF/OpenPDF/files/9578488/GlyphLayoutDocumentDin91379.pdf)

### GlyphLayoutFormDin91379.java
Fills all letters and sequences of DIN SPEC 91379 into a
PDF-form.
[GlyphLayoutFormDin91379.pdf](https://github.com/LibrePDF/OpenPDF/files/9578485/GlyphLayoutFormDin91379.pdf)

### GlyphLayoutDocumentKernLiga.java
Enables LayoutProcessor with kerning and ligatures for all fonts
[GlyphLayoutDocumentKernLiga.pdf](https://github.com/LibrePDF/OpenPDF/files/9578487/GlyphLayoutDocumentKernLiga.pdf)

### GlyphLayoutDocumentKernLigaPerFont.java
Enables LayoutProcessor with kerning and/or ligatures for specified fonts
[GlyphLayoutDocumentKernLigaPerFont.pdf](https://github.com/LibrePDF/OpenPDF/files/9578486/GlyphLayoutDocumentKernLigaPerFont.pdf)

### GlyphLayoutDocumentBidi.java
Prints bidirectional text with correct glyph layout, kerning and ligatures globally enabled
[GlyphLayoutDocumentBidi.pdf](https://github.com/LibrePDF/OpenPDF/files/9578490/GlyphLayoutDocumentBidi.pdf)

### GlyphLayoutDocumentBidiPerFont.java
Prints bidirectional text with correct glyph layout, kerning and ligatures globally enabled. Direction can be chosen per font
[GlyphLayoutDocumentBidiPerFont.pdf](https://github.com/LibrePDF/OpenPDF/files/9578489/GlyphLayoutDocumentBidiPerFont.pdf)

## Compatibilities Issues
New methods added, existing methods in LayoutProcessor are unchanged.

### CODE REVIEW

**Comment by vk-github18** [comment]
The checkstyle job did not run because of some system error.

**Comment by vk-github18** [comment]
I am thinking about more changes ...

**Comment by vk-github18** [comment]
Example for bidirectional text <code>GlyphLayoutDocumentBidi.java</code>
[GlyphLayoutDocumentBidi.pdf](https://github.com/LibrePDF/OpenPDF/files/9126273/GlyphLayoutDocumentBidi.pdf)

**Comment by asturio** [comment]
Hi @vk-github18 , the checkstyle problems were fixed on master. Can you please rebase your branch onto OpenPdf/master?

**Comment by vk-github18** [comment]
Hi @asturio, I am thinking about some updates for the final DIN norm first, and try a rebase after this.

**Comment by vk-github18** [comment]
Hi @asturio ,
my changes are done, the request is ready for integration.

**Pull request merged**
