### PR TITLE
Maven cleanups

### PR DESCRIPTION
**Pull request by asturio**
- removed unused properties
- set version properties for everything
- use dependencyManagement for all dependencies
- dependencies have no versions anymore
- pom's cleanup with "mvn tidy:pom"
- dependencies cleanup with "mvn dependency:analyze"
- removed dependencies:
  - hamcrest-core
  - hamcrest-library
  - imageio-tiff
  - junit-jupiter-engine
  - spotbugs
  - xmlgraphics-commons
- added explicit dependencies:
  - commons-io
  - hamcrest
  - jsr305

### CODE REVIEW

**Comment by andreasrosdal** [comment]
What is commons-io and jsr305 and  xml-apis used for? The removed dependencies are optional, so they need not be removed. This whole PR needs to be checked, it doesn't look correct.

**Comment by asturio** [comment]
> What is commons-io and jsr305 and xml-apis used for? 

I'm preparing a comment explaining the changes a little more extensively. xml-apis is not needed. Thanks for the notice.

**Comment by asturio** [comment]
## Dependencies cleanup

Mainly used `mvn dependency:analyze` and `mvn tidy:pom` to clean up the dependencies.

### Replaced dependencies

- hamcrest replaces
  - hamcrest-core
  - hamcrest-library

### Added dependencies

The dependencies were added, because openPDF used them before, but they weren't declared in the pom.xml.

- commons-io used in:
  - com.lowagie.text.pdf.fonts.AdvanceTypographyTest
  - com.lowagie.text.pdf.fonts.FontTest
  - previsouly transitively brought by at least `xmlgraphics-commons`
- jsr305 brings classes used 34 times in openPDF:
  - javax.annotation.Nonnull
  - javax.annotation.Nullable
  - javax.annotation.ParametersAreNonnullByDefault
  - previously transitively brought by at least `spotbugs-annotations`

### Removed dependencies
The removed dependencies are simple not needed by any code in openPDF:

- imageio-tiff
  - not used in any import in the code (package: com.twelvemonkeys.imageio.plugins.tiff)
  - no transitive dependency for it present
- junit-jupiter-engine, it suffice to have:
  - junit-jupiter-api
  - junit-jupiter-params
- spotbugs - is not really integrated. spotbugs is meant to be used as a 
  build plugin with maven, so it can break the build if bugs are found.
  A great idea, must be used correctly. But it is no dependency to openPdf
- xmlgraphics-commons
  - not used in any import in the code (package: org.apache.xmlgraphics)
  - still a transitive dependency of org.apache.xmlgraphics:fop

**Comment by asturio** [comment]
## Improved dependency tree in pdf-toolbox

### Before
```
 com.github.librepdf:pdf-toolbox:jar:1.3.23-SNAPSHOT
 +- com.github.librepdf:openpdf:jar:1.3.23-SNAPSHOT:compile
 +- org.jfree:jfreechart:jar:1.5.0:compile
 +- org.jfree:jcommon:jar:1.0.24:compile
 +- jakarta.servlet:jakarta.servlet-api:jar:5.0.0-M2:test
 +- org.bouncycastle:bcpkix-jdk15on:jar:1.66:test
 |  \- org.bouncycastle:bcprov-jdk15on:jar:1.66:test
 +- org.assertj:assertj-core:jar:3.17.2:test
 +- org.junit.jupiter:junit-jupiter-api:jar:5.7.0:test
 |  +- org.apiguardian:apiguardian-api:jar:1.1.0:test
 |  +- org.opentest4j:opentest4j:jar:1.2.0:test
 |  \- org.junit.platform:junit-platform-commons:jar:1.7.0:test
 +- org.junit.jupiter:junit-jupiter-params:jar:5.7.0:test
 +- org.junit.jupiter:junit-jupiter-engine:jar:5.7.0:test
 |  \- org.junit.platform:junit-platform-engine:jar:1.7.0:test
 +- org.mockito:mockito-core:jar:3.5.13:test
 |  +- net.bytebuddy:byte-buddy:jar:1.10.15:test
 |  +- net.bytebuddy:byte-buddy-agent:jar:1.10.15:test
 |  \- org.objenesis:objenesis:jar:3.1:test
 +- org.hamcrest:hamcrest-library:jar:2.2:test
 +- org.hamcrest:hamcrest-core:jar:2.2:test
 |  \- org.hamcrest:hamcrest:jar:2.2:test
 \- com.github.spotbugs:spotbugs:jar:4.1.3:test
    +- org.ow2.asm:asm:jar:8.0.1:test
    +- org.ow2.asm:asm-analysis:jar:8.0.1:test
    +- org.ow2.asm:asm-commons:jar:8.0.1:test
    +- org.ow2.asm:asm-tree:jar:8.0.1:test
    +- org.ow2.asm:asm-util:jar:8.0.1:test
    +- org.apache.bcel:bcel:jar:6.5.0:test
    +- net.jcip:jcip-annotations:jar:1.0:test
    +- org.dom4j:dom4j:jar:2.1.3:test
    +- org.apache.commons:commons-lang3:jar:3.11:test
    +- org.apache.commons:commons-text:jar:1.9:test
    +- org.slf4j:slf4j-api:jar:1.8.0-beta4:test
    +- com.github.spotbugs:spotbugs-annotations:jar:4.1.3:test
    |  \- com.google.code.findbugs:jsr305:jar:3.0.2:test
    +- org.json:json:jar:20200518:test
    +- jaxen:jaxen:jar:1.1.6:test
    \- net.sf.saxon:Saxon-HE:jar:10.1:test
```
### After
```
 com.github.librepdf:pdf-toolbox:jar:1.3.23-SNAPSHOT
 +- com.github.librepdf:openpdf:jar:1.3.23-SNAPSHOT:compile
 |  +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
 |  \- commons-io:commons-io:jar:2.6:compile
 +- org.jfree:jfreechart:jar:1.5.0:compile
 +- org.jfree:jcommon:jar:1.0.24:compile
 +- jakarta.servlet:jakarta.servlet-api:jar:5.0.0-M2:test
 +- org.junit.jupiter:junit-jupiter-api:jar:5.7.0:test
 |  +- org.apiguardian:apiguardian-api:jar:1.1.0:test
 |  +- org.opentest4j:opentest4j:jar:1.2.0:test
 |  \- org.junit.platform:junit-platform-commons:jar:1.7.0:test
 \- org.assertj:assertj-core:jar:3.17.2:test
```

**Comment by asturio** [comment]
## Improved dependency tree in pdf-swing

### Before
```
 com.github.librepdf:pdf-swing:jar:1.3.23-SNAPSHOT
 +- com.github.librepdf:openpdf:jar:1.3.23-SNAPSHOT:compile
 +- org.swinglabs:pdf-renderer:jar:1.0.5:compile
 +- org.dom4j:dom4j:jar:2.1.3:compile
 +- org.assertj:assertj-core:jar:3.17.2:test
 +- org.junit.jupiter:junit-jupiter-api:jar:5.7.0:test
 |  +- org.apiguardian:apiguardian-api:jar:1.1.0:test
 |  +- org.opentest4j:opentest4j:jar:1.2.0:test
 |  \- org.junit.platform:junit-platform-commons:jar:1.7.0:test
 +- org.junit.jupiter:junit-jupiter-params:jar:5.7.0:test
 +- org.junit.jupiter:junit-jupiter-engine:jar:5.7.0:test
 |  \- org.junit.platform:junit-platform-engine:jar:1.7.0:test
 +- org.mockito:mockito-core:jar:3.5.13:test
 |  +- net.bytebuddy:byte-buddy:jar:1.10.15:test
 |  +- net.bytebuddy:byte-buddy-agent:jar:1.10.15:test
 |  \- org.objenesis:objenesis:jar:3.1:test
 +- org.hamcrest:hamcrest-library:jar:2.2:test
 +- org.hamcrest:hamcrest-core:jar:2.2:test
 |  \- org.hamcrest:hamcrest:jar:2.2:test
 \- com.github.spotbugs:spotbugs:jar:4.1.3:test
    +- org.ow2.asm:asm:jar:8.0.1:test
    +- org.ow2.asm:asm-analysis:jar:8.0.1:test
    +- org.ow2.asm:asm-commons:jar:8.0.1:test
    +- org.ow2.asm:asm-tree:jar:8.0.1:test
    +- org.ow2.asm:asm-util:jar:8.0.1:test
    +- org.apache.bcel:bcel:jar:6.5.0:test
    +- net.jcip:jcip-annotations:jar:1.0:test
    +- org.apache.commons:commons-lang3:jar:3.11:test
    +- org.apache.commons:commons-text:jar:1.9:test
    +- org.slf4j:slf4j-api:jar:1.8.0-beta4:test
    +- com.github.spotbugs:spotbugs-annotations:jar:4.1.3:test
    |  \- com.google.code.findbugs:jsr305:jar:3.0.2:test
    +- org.json:json:jar:20200518:test
    +- jaxen:jaxen:jar:1.1.6:test
    \- net.sf.saxon:Saxon-HE:jar:10.1:test
```
### After
```
 com.github.librepdf:pdf-swing:jar:1.3.23-SNAPSHOT
 +- com.github.librepdf:openpdf:jar:1.3.23-SNAPSHOT:compile
 |  +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
 |  \- commons-io:commons-io:jar:2.6:compile
 +- org.swinglabs:pdf-renderer:jar:1.0.5:compile
 \- org.dom4j:dom4j:jar:2.1.3:compile
```

**Comment by asturio** [comment]
## Improved dependency tree in openpdf-fonts-extra
### Before
```
com.github.librepdf:openpdf-fonts-extra:jar:1.3.23-SNAPSHOT
 +- com.github.librepdf:openpdf:jar:1.3.23-SNAPSHOT:compile
 +- org.assertj:assertj-core:jar:3.17.2:test
 +- org.junit.jupiter:junit-jupiter-api:jar:5.7.0:test
 |  +- org.apiguardian:apiguardian-api:jar:1.1.0:test
 |  +- org.opentest4j:opentest4j:jar:1.2.0:test
 |  \- org.junit.platform:junit-platform-commons:jar:1.7.0:test
 +- org.junit.jupiter:junit-jupiter-params:jar:5.7.0:test
 +- org.junit.jupiter:junit-jupiter-engine:jar:5.7.0:test
 |  \- org.junit.platform:junit-platform-engine:jar:1.7.0:test
 +- org.mockito:mockito-core:jar:3.5.13:test
 |  +- net.bytebuddy:byte-buddy:jar:1.10.15:test
 |  +- net.bytebuddy:byte-buddy-agent:jar:1.10.15:test
 |  \- org.objenesis:objenesis:jar:3.1:test
 +- org.hamcrest:hamcrest-library:jar:2.2:test
 +- org.hamcrest:hamcrest-core:jar:2.2:test
 |  \- org.hamcrest:hamcrest:jar:2.2:test
 \- com.github.spotbugs:spotbugs:jar:4.1.3:test
    +- org.ow2.asm:asm:jar:8.0.1:test
    +- org.ow2.asm:asm-analysis:jar:8.0.1:test
    +- org.ow2.asm:asm-commons:jar:8.0.1:test
    +- org.ow2.asm:asm-tree:jar:8.0.1:test
    +- org.ow2.asm:asm-util:jar:8.0.1:test
    +- org.apache.bcel:bcel:jar:6.5.0:test
    +- net.jcip:jcip-annotations:jar:1.0:test
    +- org.dom4j:dom4j:jar:2.1.3:test
    +- org.apache.commons:commons-lang3:jar:3.11:test
    +- org.apache.commons:commons-text:jar:1.9:test
    +- org.slf4j:slf4j-api:jar:1.8.0-beta4:test
    +- com.github.spotbugs:spotbugs-annotations:jar:4.1.3:test
    |  \- com.google.code.findbugs:jsr305:jar:3.0.2:test
    +- org.json:json:jar:20200518:test
    +- jaxen:jaxen:jar:1.1.6:test
    \- net.sf.saxon:Saxon-HE:jar:10.1:test
```

### After
```
 com.github.librepdf:openpdf-fonts-extra:jar:1.3.23-SNAPSHOT
 +- com.github.librepdf:openpdf:jar:1.3.23-SNAPSHOT:compile
 |  +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
 |  \- commons-io:commons-io:jar:2.6:compile
 \- org.junit.jupiter:junit-jupiter-api:jar:5.7.0:test
    +- org.apiguardian:apiguardian-api:jar:1.1.0:test
    +- org.opentest4j:opentest4j:jar:1.2.0:test
    \- org.junit.platform:junit-platform-commons:jar:1.7.0:test
```

**Comment by asturio** [comment]
## Improved dependency tree in openpdf

### Before
```
```
 com.github.librepdf:openpdf:jar:1.3.23-SNAPSHOT
 +- org.bouncycastle:bcprov-jdk15on:jar:1.66:compile
 +- org.bouncycastle:bcpkix-jdk15on:jar:1.66:compile
 +- com.github.spotbugs:spotbugs:jar:4.1.3:compile
 |  +- org.ow2.asm:asm:jar:8.0.1:compile
 |  +- org.ow2.asm:asm-analysis:jar:8.0.1:compile
 |  +- org.ow2.asm:asm-commons:jar:8.0.1:compile
 |  +- org.ow2.asm:asm-tree:jar:8.0.1:compile
 |  +- org.ow2.asm:asm-util:jar:8.0.1:compile
 |  +- org.apache.bcel:bcel:jar:6.5.0:compile
 |  +- net.jcip:jcip-annotations:jar:1.0:compile
 |  +- org.dom4j:dom4j:jar:2.1.3:compile
 |  +- org.apache.commons:commons-lang3:jar:3.11:compile
 |  +- org.apache.commons:commons-text:jar:1.9:compile
 |  +- org.slf4j:slf4j-api:jar:1.8.0-beta4:compile
 |  +- com.github.spotbugs:spotbugs-annotations:jar:4.1.3:compile
 |  |  \- com.google.code.findbugs:jsr305:jar:3.0.2:compile
 |  +- org.json:json:jar:20200518:compile
 |  +- jaxen:jaxen:jar:1.1.6:runtime
 |  \- net.sf.saxon:Saxon-HE:jar:10.1:runtime
 +- com.twelvemonkeys.imageio:imageio-tiff:jar:3.6:compile
 |  +- com.twelvemonkeys.imageio:imageio-core:jar:3.6:compile
 |  +- com.twelvemonkeys.imageio:imageio-metadata:jar:3.6:compile
 |  +- com.twelvemonkeys.common:common-lang:jar:3.6:compile
 |  +- com.twelvemonkeys.common:common-io:jar:3.6:compile
 |  \- com.twelvemonkeys.common:common-image:jar:3.6:compile
 +- org.apache.xmlgraphics:fop:jar:2.5:compile
 |  +- org.apache.xmlgraphics:fop-util:jar:2.5:compile
 |  +- org.apache.xmlgraphics:fop-events:jar:2.5:compile
 |  |  +- com.thoughtworks.qdox:qdox:jar:1.12:compile
 |  |  \- org.apache.ant:ant:jar:1.8.2:compile
 |  |     \- org.apache.ant:ant-launcher:jar:1.8.2:compile
 |  \- org.apache.xmlgraphics:fop-core:jar:2.5:compile
 |     +- org.apache.xmlgraphics:batik-anim:jar:1.13:compile
 |     |  +- org.apache.xmlgraphics:batik-css:jar:1.13:compile
 |     |  +- org.apache.xmlgraphics:batik-dom:jar:1.13:compile
 |     |  |  +- xalan:xalan:jar:2.7.2:compile
 |     |  |  |  \- xalan:serializer:jar:2.7.2:compile
 |     |  |  \- xml-apis:xml-apis:jar:1.4.01:compile
 |     |  +- org.apache.xmlgraphics:batik-ext:jar:1.13:compile
 |     |  +- org.apache.xmlgraphics:batik-parser:jar:1.13:compile
 |     |  +- org.apache.xmlgraphics:batik-shared-resources:jar:1.13:compile
 |     |  +- org.apache.xmlgraphics:batik-svg-dom:jar:1.13:compile
 |     |  +- org.apache.xmlgraphics:batik-util:jar:1.13:compile
 |     |  |  +- org.apache.xmlgraphics:batik-constants:jar:1.13:compile
 |     |  |  \- org.apache.xmlgraphics:batik-i18n:jar:1.13:compile
 |     |  \- xml-apis:xml-apis-ext:jar:1.3.04:compile
 |     +- org.apache.xmlgraphics:batik-awt-util:jar:1.13:compile
 |     +- org.apache.xmlgraphics:batik-bridge:jar:1.13:compile
 |     |  +- org.apache.xmlgraphics:batik-script:jar:1.13:compile
 |     |  \- org.apache.xmlgraphics:batik-xml:jar:1.13:compile
 |     +- org.apache.xmlgraphics:batik-extension:jar:1.13:compile
 |     +- org.apache.xmlgraphics:batik-gvt:jar:1.13:compile
 |     +- org.apache.xmlgraphics:batik-transcoder:jar:1.13:compile
 |     |  \- org.apache.xmlgraphics:batik-svggen:jar:1.13:compile
 |     +- javax.servlet:servlet-api:jar:2.2:compile
 |     +- org.apache.pdfbox:fontbox:jar:2.0.16:compile
 |     +- javax.media:jai-core:jar:1.1.3:compile
 |     \- com.sun.media:jai-codec:jar:1.1.3:compile
 +- org.apache.xmlgraphics:xmlgraphics-commons:jar:2.4:compile
 |  +- commons-io:commons-io:jar:1.3.1:compile
 |  \- commons-logging:commons-logging:jar:1.0.4:compile
 +- org.hamcrest:hamcrest-core:jar:2.2:test
 |  \- org.hamcrest:hamcrest:jar:2.2:test
 +- org.assertj:assertj-core:jar:3.17.2:test
 +- org.junit.jupiter:junit-jupiter-api:jar:5.7.0:test
 |  +- org.apiguardian:apiguardian-api:jar:1.1.0:test
 |  +- org.opentest4j:opentest4j:jar:1.2.0:test
 |  \- org.junit.platform:junit-platform-commons:jar:1.7.0:test
 +- org.junit.jupiter:junit-jupiter-params:jar:5.7.0:test
 +- org.junit.jupiter:junit-jupiter-engine:jar:5.7.0:test
 |  \- org.junit.platform:junit-platform-engine:jar:1.7.0:test
 +- org.mockito:mockito-core:jar:3.5.13:test
 |  +- net.bytebuddy:byte-buddy:jar:1.10.15:test
 |  +- net.bytebuddy:byte-buddy-agent:jar:1.10.15:test
 |  \- org.objenesis:objenesis:jar:3.1:test
 \- org.hamcrest:hamcrest-library:jar:2.2:test
```
### After
 com.github.librepdf:openpdf:jar:1.3.23-SNAPSHOT
 +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
 +- commons-io:commons-io:jar:2.6:compile
 +- org.bouncycastle:bcprov-jdk15on:jar:1.66:compile
 +- org.bouncycastle:bcpkix-jdk15on:jar:1.66:compile
 +- org.apache.xmlgraphics:fop:jar:2.5:compile
 |  +- org.apache.xmlgraphics:fop-util:jar:2.5:compile
 |  |  \- org.apache.xmlgraphics:xmlgraphics-commons:jar:2.4:compile
 |  +- org.apache.xmlgraphics:fop-events:jar:2.5:compile
 |  |  +- com.thoughtworks.qdox:qdox:jar:1.12:compile
 |  |  \- org.apache.ant:ant:jar:1.8.2:compile
 |  |     \- org.apache.ant:ant-launcher:jar:1.8.2:compile
 |  \- org.apache.xmlgraphics:fop-core:jar:2.5:compile
 |     +- org.apache.xmlgraphics:batik-anim:jar:1.13:compile
 |     |  +- org.apache.xmlgraphics:batik-css:jar:1.13:compile
 |     |  +- org.apache.xmlgraphics:batik-dom:jar:1.13:compile
 |     |  |  +- xalan:xalan:jar:2.7.2:compile
 |     |  |  |  \- xalan:serializer:jar:2.7.2:compile
 |     |  |  \- xml-apis:xml-apis:jar:1.4.01:compile
 |     |  +- org.apache.xmlgraphics:batik-ext:jar:1.13:compile
 |     |  +- org.apache.xmlgraphics:batik-parser:jar:1.13:compile
 |     |  +- org.apache.xmlgraphics:batik-shared-resources:jar:1.13:compile
 |     |  +- org.apache.xmlgraphics:batik-svg-dom:jar:1.13:compile
 |     |  +- org.apache.xmlgraphics:batik-util:jar:1.13:compile
 |     |  |  +- org.apache.xmlgraphics:batik-constants:jar:1.13:compile
 |     |  |  \- org.apache.xmlgraphics:batik-i18n:jar:1.13:compile
 |     |  \- xml-apis:xml-apis-ext:jar:1.3.04:compile
 |     +- org.apache.xmlgraphics:batik-awt-util:jar:1.13:compile
 |     +- org.apache.xmlgraphics:batik-bridge:jar:1.13:compile
 |     |  +- org.apache.xmlgraphics:batik-script:jar:1.13:compile
 |     |  \- org.apache.xmlgraphics:batik-xml:jar:1.13:compile
 |     +- org.apache.xmlgraphics:batik-extension:jar:1.13:compile
 |     +- org.apache.xmlgraphics:batik-gvt:jar:1.13:compile
 |     +- org.apache.xmlgraphics:batik-transcoder:jar:1.13:compile
 |     |  \- org.apache.xmlgraphics:batik-svggen:jar:1.13:compile
 |     +- commons-logging:commons-logging:jar:1.0.4:compile
 |     +- javax.servlet:servlet-api:jar:2.2:compile
 |     +- org.apache.pdfbox:fontbox:jar:2.0.16:compile
 |     +- javax.media:jai-core:jar:1.1.3:compile
 |     \- com.sun.media:jai-codec:jar:1.1.3:compile
 +- org.junit.jupiter:junit-jupiter-api:jar:5.7.0:test
 |  +- org.apiguardian:apiguardian-api:jar:1.1.0:test
 |  +- org.opentest4j:opentest4j:jar:1.2.0:test
 |  \- org.junit.platform:junit-platform-commons:jar:1.7.0:test
 +- org.junit.jupiter:junit-jupiter-params:jar:5.7.0:test
 +- org.assertj:assertj-core:jar:3.17.2:test
 +- org.mockito:mockito-core:jar:3.5.13:test
 |  +- net.bytebuddy:byte-buddy:jar:1.10.15:test
 |  +- net.bytebuddy:byte-buddy-agent:jar:1.10.15:test
 |  \- org.objenesis:objenesis:jar:3.1:test
 \- org.hamcrest:hamcrest:jar:2.2:test
```

**Comment by andreasrosdal** [comment]
commons-io should have test scope, since it's only used in tests.

I think we should get input on this from others.
@albfernandez @codecracker2014 @V-F @daviddurand

**Comment by andreasrosdal** [comment]
The dependency on jsr305 can be made as test scope also, since the annotations are used by Spotbugs.

So no new dependencies are required for using OpenPDF as a library.

**Comment by codecracker2014** [comment]
commons-io was coming as transitive dependency from org.apache.xmlgraphics:fop, used by fop.

**Comment by V-F** [comment]
> commons-io should have test scope, since it's only used in tests.
> 
> I think we should get input on this from others.
> @albfernandez @codecracker2014 @V-F @daviddurand

Fully agreed. Great job.

**Comment by asturio** [comment]
commons-io is now scope test as the classes are really only used in the tests. fop will bring it transitively for it's use.
jsr305 is still scope compile, as we really use their classes in production code, like in `Font`, `Chunk`, `TextField` and other 31 classes.
The PR stays open for more input and feedback.

**Comment by prashantbhat** [comment]
Some observations on changes to `openpdf` module:
* `requires static xmlgraphics.commons;` can be removed from module-info, as it is not a dependency anymore.
* `jsr305` is not included in module-info but it may not be required as these annotations are not accessed at runtime
* `META-INF/MANIFEST.MF` doesn't include `Automatic-Module-Name` now as `java-module-name` is not present in  pom.xml (but it is still present in other modules).

**Comment by asturio** [comment]
> Some observations on changes to `openpdf` module:
> 
>     * `requires static xmlgraphics.commons;` can be removed from module-info, as it is not a dependency anymore.
> 
>     * `jsr305` is not included in module-info but it may not be required as these annotations are not accessed at runtime
> 
>     * `META-INF/MANIFEST.MF` doesn't include `Automatic-Module-Name` now as `java-module-name` is not present in  pom.xml (but it is still present in other modules).

Great finding. I just corrected the pom.xml and module-info.

**Comment by asturio** [comment]
I tested [flying-saucer-openpdf ](https://github.com/flyingsaucerproject/flyingsaucer/tree/openpdf )with this SNAPSHOT, and it worked. It also detected that in maven, other projects will need to use maven-bundle-plugin 3.5.0+, because of the Java 9 classes in the jar.

**Pull request merged**
