### PR TITLE
fix for invalid ecdsa oids for signatures

### PR DESCRIPTION
**Pull request by Lonzak**
Corrected the OIDs for several algorithms (RSA, DSA and ECDSA) when signing with openPDF.

### CODE REVIEW

**Comment by Lonzak** [comment]
@mkl-public Code review appreciated :-)

**Review by mkl-public — COMMENTED** [review]
The changes in `ExceptionConverter` are unrelated (and IMO mostly unnecessary, but that is indeed a matter of opinion). Nonetheless, they don't break anything either.

The `PdfPKCS7` changes are pivotal and look appropriate. You may consider adding tests for at least a representative selection of the Algorithms.

Also consider the Codacy remarks, they are meant to introduce a common style which in turn improves readability.

**Comment by Lonzak** [comment]
Fixed the codacy issues.

**Comment by asturio** [comment]
Looks good. Are you ready with your changes, @Lonzak ?

**Comment by asturio** [comment]
Merged that. If you want, you may add some tests for this.

**Comment by andreasrosdal** [comment]
This needs to be ported to the main branch also. @asturio @Lonzak

**Pull request merged**
