### PR TITLE
WIP : Generate version number at build time

### LINKED ISSUE #261: Incorrect information about the library
The library version is currently parsed from the manifest file in the 
`com.lowagie.text.VersionBean` class . If a program is built as a single jar file the manifest file of the library will be replaced and incorrect information will be parsed. This information is used by creation of pdf document (see: `com.lowagie.text.pdf.PdfPages` line: 152 / `com.lowagie.text.pdf.PdfStamperImp` line: 170. The constant `com.lowagie.text.pdf.PdfName.ITXT` is also no longer relevant).  It probably makes sense to store the library information in a property file or as constant values.

### PR DESCRIPTION
**Pull request by sixdouglas**
Getting the VersionBean filled right by OpenPDF release version to fix #261 .

@andreasrosdal @asturio do you think that other data, originally extracted from the Manifest, should be extracted in the same way, from the properties file. Meaning do we still need to read the Manifest.

### CODE REVIEW

**Comment by asturio** [comment]
Is travis working properly?

**Comment by sixdouglas** [comment]
Yes. I haven’t fixed the unit tests yet

**Comment by andreasrosdal** [comment]
This pull request is of too poor quality. Please submit a working proposal where the tests pass and you think it is worthy of submission.

**Comment by andreasrosdal** [comment]
I'm not entirely sure that we should mess around changing this too much, unless we have a very good alternative implementation.

**Comment by sixdouglas** [comment]
I didn't plan to merge this in this state. This was just for the discussion. The WIP in the title stands for Work In Progress. But I guess this is a common naming convention. I should have been more clear.

**Pull request closed without merging**
