### PR TITLE
solve the bug #687: Image in Paragraph has unexpected behavior

### PR DESCRIPTION
**Pull request by ThreeHmeng**
## Description of the Bugfix

Related Issue: #687 

## Unit-Tests for the Bugfix
- No unittests added

## Compatibilities Issues
- Not checked

## Testing details
- No testing details.

### CODE REVIEW

**Comment by ThreeHmeng** [comment]
Hi, @asturio ,I think I fixed the bug successfully,and what do u think?

**Comment by ObsisMc** [comment]
Maybe it works, but I think suggestion proposed by Marc Campforts in comment is the same as yours and his/her code is simpler.

**Comment by asturio** [comment]
> suggestion proposed by Marc Campforts in comment

Hi @ObsisMc , which comment are you referring?

**Comment by asturio** [comment]
@ThreeHmeng Can you fix your test? They try to create a file in E:\ but there is no guaranty this Path exists. Can you create the files without a Path, or maybe in target?

**Comment by ObsisMc** [comment]
@asturio 
Here
image

**Comment by ThreeHmeng** [comment]
@asturio ,sure! I have finished it.

**Comment by asturio** [comment]
@ThreeHmeng 
I think the remark of @ObsisMc is correct. And adding a carriageReturn() in every case: will add many carriageReturn()s, because the code has no break, and you will fall through other cases.
In the case of JPEG, e.g., there will be 4 carriageReturns.

Probably having only one CR on line 751 (now after IMGTEMPLATE), and removing the others in the lines above will have the desired effect.

**Comment by asturio** [comment]
Just created an example how to accomplish the desired effect of #687 here:
pdf-toolbox/src/test/java/org/librepdf/openpdf/text/pdf/ImageAfterTextExample.java

So this PR is obsolete, or more precisely, it would change the behavior of OpenPDF compared to iText 5.

**Pull request closed without merging**
