### PR TITLE
Added c9.io developer mini guide to README.md

### PR DESCRIPTION
**Pull request by santeriv**

### CODE REVIEW

**Comment by andreasrosdal** [comment]
Thanks for the contibution to OpenPDF. Why should c9.io be added to the README?

**Comment by santeriv** [comment]
I like to use browser only editing capabilities, and I happen to use c9.io for that. I considered first creating new DEVELOPMENT.md where it could be said. Browser is second motivation is as long it can be done free, which primarily. It applies for me using heroku, github, c9.io, phonegap. For example I stopped to use nodejitsu when they dropped freemium. Do you have ideas how this guide could be contributed, if at all? For me all are ok, because even rejected I ve contributed a PR.

**Comment by andreasrosdal** [comment]
I'm ok with this change, but it will have to be accepted by @bengolder also.

**Comment by nwinkler** [comment]
Wouldn't this be more appropriate for a Wiki page?

**Comment by andreasrosdal** [comment]
Yes, I agree that a Wiki page is more appropriate.

**Comment by nwinkler** [comment]
It doesn't look like the Wiki is enabled on this project. 

@andreasrosdal Can you enable the Wiki?

**Comment by andreasrosdal** [comment]
That has to be fine by @bengolder , I only have developer access.

**Comment by bengolder** [comment]
I'm sorry @andreasrosdal you should have admin! I'll enable the wiki and change the permissions for you

**Comment by bengolder** [comment]
Done. Apologies for not doing that earlier

**Pull request closed without merging**
