### PR TITLE
Code cleanup (Add library dependencies, remove old custom code)

### PR DESCRIPTION
**Pull request by andreasrosdal**
This is part of the ongoing work on Issue #89, where the source code is cleaned up, old custom source code is replaced by using software libraries instead. 

- Add dependency to Apache Commons commons-text. Remove SimpleXMLParser.escapeXML. 
- Deprecate SimpleXMLParser. Should use a XML parser from a library instead from now on.
- Removed ExceptionConverter. Added simpler ExceptionUtil class.
- Add dependency to Apache Commons IO and Apache Commons Compress. Remove the LZWDecoder class.
- Add dependency on Sanselan (Apache Commons Imaging) and use that to load images. Remove old custom BMP, GIF, PNG, TIF and JBIG image codecs.
- Removed the pdf-rtf module.
- Remove the class BidiOrder. Remove support for bidirectional text support.

As a result of this the contents of misc_licenses.txt is reduced considerably, making OpenPDF significantly more LGPL/MPL consistent. The only remaining class mentioned there now is SimpleXMLParser. That class is very-non-trivial to replace, and it is still in use in iText, so it should be safe.

I intend to merge this pull-request in some days if there are no strong objections.

### CODE REVIEW

**Comment by andreasrosdal** [comment]
@PascalSchumacher 

What code do you suggest we replace ExceptionHelper#wrapOrThrow with? (I had to replace it with something, and had limited time.) Using a library seems like a sane thing to do. If you can please just paste in some replacement Java-code which can be used with LGPL/MPL terms, then I can consider to use that instead.

ExceptionHelper#wrapOrThrow is better than using ExceptionConverter, because of possible unknown licensing issues.

**Comment by PascalSchumacher** [comment]
By the way `commons-text` version`1.4` requires Java 8 while Open PDF seems to require Java 7 (https://github.com/LibrePDF/OpenPDF/blob/master/pom.xml#L46). The last Java 7 compatible `commons-text` version was `1.3`.

**Comment by andreasrosdal** [comment]
@kasperschnack Please open bugs about soecifics you are missing. 

@gexclaude Using libraries will allow this project to focus more on the core functionality. Apache Commons are widely used libraries which should be fine to use for almost all projects. Some of the dependencies can be made optional, pull-requests are welcone.

Please open bugreports about specific issues you might have.

**Comment by sagendejonge** [comment]
Why was bidirectional text support removed?  Is there a new better way it can be supported now?

**Comment by gexclaude** [comment]
> In my opinion, adding a dependency on commons-text in a library like OpenPDF just to remove a method doing xml escaping is overkill.
> Think about users who will have to resolve version conflicts or users who don't have clean dependency management. (See [this example](https://dzone.com/articles/10-effective-tips-on-using-maven) recommending to explicitly repeat transitive dependencies in their pom, forgetting that it will defeat your library updating its dependencies when needed.)
> 

that is what meant with my previous comment. Keeping the number of dependencies small for a library, it eases its usage, which is a clear benefit. But of course, I don't mean to avoid dependencies at all costs.

**Pull request merged**
