### PR TITLE
Fb 001 java8 generics

### PR DESCRIPTION
**Pull request by fvbassi**
Hello.
I did a refactoring on the project to make use of typed generics all over the place.
Some changes may have a minor impact on the preservation of the current API.

In particular, the class Phrase used to extend ArrayList. It's mostly impossible to keep this structure, because using a typed ArrayList (something like 'class Phrase extends ArrayList') creates some clashes between the ArrayList bridge method and other similar methods in the API.
So, I decided to change the signature of the class and make the ArrayList a field of the class (this also make encapsulation more explicit).
Please review it.

Please also note that I didn't have the opportunity to do extensive review of the code and proper testing.

### CODE REVIEW

**Comment by andreasrosdal** [comment]
The tests are failing:  https://travis-ci.org/LibrePDF/OpenPDF/builds/501396688?utm_source=github_status&utm_medium=notification

**Comment by fvbassi** [comment]
I see there are tons of tests failing.
I will work on it.

How can I run the test on my local branch?

– fb

**Comment by andreasrosdal** [comment]
mvn install -Dgpg.skip

**Comment by andreasrosdal** [comment]
When these tests break, it means that existing users of OpenPDF will likely face similiar problems. Please consider this, and find good solutions. If we have to break the existing API, we can, if there are very good reasons for doing it.

**Comment by andreasrosdal** [comment]
@daviddurand @rtfarte @noavarice  Can you please also follow this pull request?

**Comment by fvbassi** [comment]
That's absolutely fine. Give me some time to check what's going on and find
proper solutions.

–fb

Il mar 5 mar 2019, 8:11 AM Andreas Rosdal <notifications@github.com> ha
scritto:

**Comment by andreasrosdal** [comment]
@fvbassi Great! We want the result to be as good as possible.

**Comment by noavarice** [comment]
@fvbassi Really nice work, but for ease of both adding new patches and reviewing them, please, make PRs a more atomic, especially when there is a problem with failing tests)

**Comment by andreasrosdal** [comment]
@fvbassi I suggest you decide gor yourself if you want to split it up. This is a very large and complex change, so it might be too difficult to split up.

Fixing what breaks the tests should be first priority.

**Comment by fvbassi** [comment]
I agree.
Then I'll try to see how to split it.
I know that such a big patch would be rejected by most projects. But it's
also true that the change is for just one purpose: fix the typization.
Unfortunately it will take some days: I don't have spare time this week.

Il mer 6 mar 2019, 7:05 AM Andreas Rosdal <notifications@github.com> ha
scritto:

**Comment by andreasrosdal** [comment]
@fvbassi Any news on this?

**Comment by andreasrosdal** [comment]
I will just close this pull request for now. 
Please open a new pull request for the next proposal.

**Comment by fvbassi** [comment]
Good

Il sab 9 mar 2019, 10:00 PM Andreas Rosdal <notifications@github.com> ha
scritto:

**Comment by andreasrosdal** [comment]
@fvbassi I hope you are still interested in completing this modernization. If is a very difficult task to get correct, though.

**Comment by fvbassi** [comment]
Yes, I am. Unfortunately I don't have too much time to work on it.
I hope I'll be able to bring it to a reasonable state in the next weekend.
I'm sorry for the delay…
– fb

**Comment by fvbassi** [comment]
By the way: I already see some work in progress. I will merge it in.

**Pull request closed without merging**
