### PR TITLE
Test unicode

### PR DESCRIPTION
**Pull request by asturio**
Hi @tlxtellef , @daviddurand and @bengolder 

This a the last branch I had "in the air".
This fixes nothing but checks:
- If the POM Version is the same as the "hardcoded" Version.
- Some tests for creating PDFs
- Some test for unicode fonts (not really testable (now?), but generates a PDF, which can be controlled manually).

PS - If I'm now a contributor, I could work directly here, instead of my "private repo", right?
PS2 - I don't know any other way to discuss something here. Any hints?

### CODE REVIEW

**Comment by andreasrosdal** [comment]
There is a test failing.

**Comment by tlxtellef** [comment]
@asturio Yes, you can work in this repo. So instead of separate repo with pull requests in, you could create a branch, work on that and set up a pull request for review.

When it comes to communication I thing we should look into some sort of free chat solution like Slack or Discord. Any thoughts or ideas about that?

**Comment by asturio** [comment]
Test is now ok. I use already slack. But I'm open for other suggestions. (@tlxtellef)

**Comment by asturio** [comment]
@LibrePDF/openpdf I just selected @tlxtellef to be a reviewer of this pull request. Should we always do like this, or should a random developer pick the pull request?

I also created this new "Team" so everyone would be notified by using @LibrePDF/openpdf .

**Pull request merged**
