### PR TITLE
Added support of PdfIndirectObject for coordinates in /Rect, /BBox

### PR DESCRIPTION
**Pull request by sa-sh**
## Description of the Bugfix

If annotation has /Rect which constist of PdfIndirectReference instead of PdfNumber, form flattening does not work
It throws exception like:
```
java.lang.IllegalArgumentException: Invalid argument. Float value (coordinate) expected! But was 8 0 R

	at com.lowagie.text.pdf.PdfRectangle.convertToFloat(PdfRectangle.java:169)
	at com.lowagie.text.pdf.PdfRectangle.<init>(PdfRectangle.java:163)
	at com.lowagie.text.pdf.PdfStamperImp.flatFields(PdfStamperImp.java:983)
	at com.lowagie.text.pdf.PdfStamperImp.close(PdfStamperImp.java:224)
	at com.lowagie.text.pdf.PdfStamper.close(PdfStamper.java:397)
```

## Unit-Tests for the new Feature/Bugfix

[+] Unit-Tests added to cover the bug

## Testing details

For testing added PDF that causes issue during form flattening, 
with this fix - test passed

### CODE REVIEW

**Comment by sa-sh** [comment]
is "1.3-java8" branch still open for bugfixes ?

**Comment by asturio** [comment]
> is "1.3-java8" branch still open for bugfixes ?

Yes.

**Comment by asturio** [comment]
@sa-sh You may also cherry-pick these changes to 1.4 and master, so the newer versions have also the fixes.

**Comment by sa-sh** [comment]
thank you, i will create another PR for master

**Pull request merged**
